### ISSUE TITLE
Application exception for Linux

### ISSUE THREAD

**Issue by aaronang** [jimhommes/BubbleBobble#215]
```
/usr/java/jdk1.8.0_60/bin/java -Didea.launcher.port=7532 -Didea.launcher.bin.path=/home/awzang/applications/idea-IC-141.2735.5/bin -Dfile.encoding=UTF-8 -classpath /usr/java/jdk1.8.0_60/jre/lib/jfxswt.jar:/usr/java/jdk1.8.0_60/jre/lib/management-agent.jar:/usr/java/jdk1.8.0_60/jre/lib/plugin.jar:/usr/java/jdk1.8.0_60/jre/lib/charsets.jar:/usr/java/jdk1.8.0_60/jre/lib/jfr.jar:/usr/java/jdk1.8.0_60/jre/lib/rt.jar:/usr/java/jdk1.8.0_60/jre/lib/javaws.jar:/usr/java/jdk1.8.0_60/jre/lib/jsse.jar:/usr/java/jdk1.8.0_60/jre/lib/resources.jar:/usr/java/jdk1.8.0_60/jre/lib/deploy.jar:/usr/java/jdk1.8.0_60/jre/lib/jce.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/sunjce_provider.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/jaccess.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/sunec.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/zipfs.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/jfxrt.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/nashorn.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/dnsns.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/sunpkcs11.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/cldrdata.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/localedata.jar:/home/awzang/code/bubble-bobble/group-07/target/classes:/home/awzang/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/awzang/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/awzang/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:/home/awzang/applications/idea-IC-141.2735.5/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain launcher.Launcher
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965

** (java:4056): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-gjb89BlWYV: Connection refused
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Location is required.
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3207)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
    at launcher.Launcher.start(Launcher.java:45)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$50(GtkApplication.java:139)
    ... 1 more

Process finished with exit code 1
```

**Comment by aaronang** [comment]
This is still not fixed for Linux systems.

```
/usr/java/jdk1.8.0_60/bin/java -Didea.launcher.port=7532 -Didea.launcher.bin.path=/home/awzang/applications/idea-IC-141.2735.5/bin -Dfile.encoding=UTF-8 -classpath /usr/java/jdk1.8.0_60/jre/lib/jfxswt.jar:/usr/java/jdk1.8.0_60/jre/lib/management-agent.jar:/usr/java/jdk1.8.0_60/jre/lib/plugin.jar:/usr/java/jdk1.8.0_60/jre/lib/charsets.jar:/usr/java/jdk1.8.0_60/jre/lib/jfr.jar:/usr/java/jdk1.8.0_60/jre/lib/rt.jar:/usr/java/jdk1.8.0_60/jre/lib/javaws.jar:/usr/java/jdk1.8.0_60/jre/lib/jsse.jar:/usr/java/jdk1.8.0_60/jre/lib/resources.jar:/usr/java/jdk1.8.0_60/jre/lib/deploy.jar:/usr/java/jdk1.8.0_60/jre/lib/jce.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/sunjce_provider.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/jaccess.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/sunec.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/zipfs.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/jfxrt.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/nashorn.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/dnsns.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/sunpkcs11.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/cldrdata.jar:/usr/java/jdk1.8.0_60/jre/lib/ext/localedata.jar:/home/awzang/code/bubble-bobble/group-07/target/classes:/home/awzang/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/awzang/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/awzang/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:/home/awzang/applications/idea-IC-141.2735.5/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain launcher.Launcher
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
    at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
    at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
    at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
    at launcher.Launcher.setMusicSong(Launcher.java:74)
    at launcher.Launcher.initMusicPlayer(Launcher.java:50)
    at launcher.Launcher.start(Launcher.java:45)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$50(GtkApplication.java:139)
    ... 1 more
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
    at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:224)
    at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:104)
    at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:467)
    ... 13 more

Process finished with exit code 1
```

Anyways, do not focus on this issue.
